import { ADVENTURE_VERSION } from '../shared/adventure-regions.mjs';
import { BOATING } from '../shared/boats.mjs';
import { EARTH } from '../shared/paleo-geography.mjs';
import { RIDING } from '../shared/riding.mjs';
import { NPC, WORLD } from '../shared/world.mjs';
import { residentSnapshots } from '../shared/village-life.mjs';
import { VILLAGE, villageDay } from '../shared/village-sites.mjs';
export function snapshot(
  room,
  includeWorld = false,
  now = Date.now(),
): import('../shared/snapshots.mjs').GameSnapshot {
  return {
    residents: residentSnapshots(room),
    boatingVersion: BOATING.version,
    adventureVersion: ADVENTURE_VERSION,
    boats: room.boats.map(({ id, x, z, facing, radius, riderId, speed, moving, running }) => ({
      id,
      x,
      z,
      facing,
      radius,
      riderId,
      speed,
      moving,
      running,
    })),
    type: 'state',
    ridingVersion: RIDING.version,
    combatVersion: 3,
    characterVersion: 2,
    enemyVersion: 1,
    worldVersion: WORLD.version,
    playerLimit: room.playerLimit ?? WORLD.maxPlayers,
    worldWidth: WORLD.width,
    worldDepth: WORLD.depth,
    epochYearsBP: EARTH.epochYearsBP,
    room: room.name,
    serverTime: now,
    projectiles: (room.projectiles || []).map(
      ({ id, ownerId, x, z, dx, dz, createdAt, updatedAt, travelled, kind, elevation }) => ({
        id,
        ownerId,
        x,
        z,
        dx,
        dz,
        createdAt,
        updatedAt,
        travelled,
        kind,
        elevation,
      }),
    ),
    projectileImpacts: (room.projectileImpacts || []).map((effect) => ({ ...effect })),
    animals: room.animals.map(
      ({
        id,
        x,
        z,
        facing,
        speed,
        scale,
        radius,
        clip,
        phase,
        health,
        maxHealth,
        meatRemaining,
        phaseStartedAt,
        riderId,
      }) => ({
        id,
        x,
        z,
        facing,
        speed,
        scale,
        radius,
        clip,
        phase,
        health,
        maxHealth,
        meatRemaining,
        phaseStartedAt,
        riderId,
      }),
    ),
    enemies: (room.enemies || []).map(
      ({
        id,
        modelKey,
        name,
        hostile,
        x,
        z,
        scale,
        facing,
        speed,
        radius,
        clip,
        phase,
        health,
        maxHealth,
        phaseStartedAt,
        behavior,
        targetId,
        attackSequence,
        attackAt,
        hitSequence,
        hitAt,
      }) => ({
        id,
        modelKey,
        name,
        hostile,
        x,
        z,
        scale,
        facing,
        speed,
        radius,
        clip,
        phase,
        health,
        maxHealth,
        phaseStartedAt,
        behavior,
        targetId,
        attackSequence,
        attackAt,
        hitSequence,
        hitAt,
      }),
    ),
    players: [...room.players.values()].map(
      ({
        id,
        name,
        species,
        gender,
        x,
        z,
        radius,
        color,
        inventory,
        gathered,
        tool,
        ready,
        energy,
        facing,
        moving,
        running,
        speed,
        attackSequence,
        attackAt,
        cookingEndsAt,
        cookingKind,
        fishing,
        coastalActivity,
        spearHead,
        hurtSequence,
        hurtAt,
        defeatSequence,
        downedUntil,
        invulnerableUntil,
        mountId,
        boatId,
        adventure,
        gulf,
      }) => ({
        id,
        name,
        species,
        gender,
        x,
        z,
        radius,
        color,
        inventory: { ...inventory },
        gathered: gathered ?? 0,
        tool,
        ready,
        energy,
        facing,
        moving,
        running,
        speed,
        attackSequence,
        attackAt,
        cookingEndsAt,
        cookingKind,
        fishing: fishing
          ? { spotId: fishing.spotId, startedAt: fishing.startedAt, endsAt: fishing.endsAt }
          : null,
        coastalActivity: coastalActivity
          ? {
              kind: coastalActivity.kind,
              siteId: coastalActivity.siteId,
              startedAt: coastalActivity.startedAt,
              endsAt: coastalActivity.endsAt,
            }
          : null,
        spearHead: spearHead === 'obsidian' ? 'obsidian' : 'wood',
        hurtSequence,
        hurtAt,
        defeatSequence,
        downedUntil,
        invulnerableUntil,
        mountId,
        boatId,
        adventure: JSON.parse(JSON.stringify(adventure ?? { regions: {} })),
        gulf: gulf ? structuredClone(gulf) : undefined,
      }),
    ),
    ...(includeWorld
      ? {
          resources: room.resources.map(({ regeneratedAt, ...resource }) => ({ ...resource })),
          camp: { ...room.camp },
          cookingFires: room.cookingFires,
          npc: { ...NPC },
          gulf: structuredClone(room.gulf),
        }
      : {}),
    day: villageDay(now, room.createdAt),
    dayProgress: (Math.max(0, now - room.createdAt) % VILLAGE.dayMs) / VILLAGE.dayMs,
    completed: room.camp.level >= 1,
  };
}
