import { ADVENTURE_VERSION } from '../shared/adventure-regions.mjs';
import { BOATING } from '../shared/boats.mjs';
import { EARTH } from '../shared/paleo-geography.mjs';
import { RIDING } from '../shared/riding.mjs';
import { NPC, WORLD } from '../shared/world.mjs';
import { residentSnapshots } from '../shared/village-life.mjs';
import { householdSnapshots } from '../shared/household-life.mjs';
import { VILLAGE, villageDay } from '../shared/village-sites.mjs';
import { maritimeWeather } from '../shared/maritime-weather.mjs';
import { barterSnapshots } from '../shared/barter.mjs';
import { activeMapPins } from '../shared/map-pins.mjs';
export function snapshot(
  room,
  includeWorld = false,
  now = Date.now(),
): import('../shared/snapshots.mjs').GameSnapshot {
  return {
    mapPins: activeMapPins(room, now),
    barters: barterSnapshots(room),
    residents: residentSnapshots(room),
    households: householdSnapshots(room),
    boatingVersion: BOATING.version,
    adventureVersion: ADVENTURE_VERSION,
    boats: room.boats.map(({ id, x, z, facing, radius, riderId, speed, moving, running }) => ({
      id,
      x,
      z,
      facing,
      radius,
      riderId,
      speed,
      moving,
      running,
    })),
    type: 'state',
    ridingVersion: RIDING.version,
    combatVersion: 3,
    characterVersion: 2,
    enemyVersion: 1,
    worldVersion: WORLD.version,
    playerLimit: room.playerLimit ?? WORLD.maxPlayers,
    worldWidth: WORLD.width,
    worldDepth: WORLD.depth,
    epochYearsBP: EARTH.epochYearsBP,
    room: room.name,
    serverTime: now,
    maritime: maritimeWeather(now, room.createdAt ?? now),
    // Player light orbs and the sorcerer's red hex bolts share one list; `kind`
    // tells the renderer which colour to draw.
    projectiles: [...(room.projectiles || []), ...(room.hexBolts || [])].map(
      ({ id, ownerId, x, z, dx, dz, speed, createdAt, updatedAt, travelled, kind, elevation }) => ({
        id,
        ownerId,
        x,
        z,
        dx,
        dz,
        speed,
        createdAt,
        updatedAt,
        travelled,
        kind,
        elevation,
      }),
    ),
    projectileImpacts: (room.projectileImpacts || []).map((effect) => ({ ...effect })),
    poisonShots: (room.poisonShots ?? []).map((shot) => ({ ...shot })),
    poisonSplashes: (room.poisonSplashes ?? []).map((splash) => ({ ...splash })),
    hexBursts: (room.hexBursts || []).map(
      ({ id, ownerId, x, z, elevation, radius, startedAt, at, detonatedAt }) => ({
        id,
        ownerId,
        x,
        z,
        elevation,
        radius,
        startedAt,
        at,
        detonatedAt: detonatedAt ?? null,
      }),
    ),
    animals: room.animals.map(
      ({
        id,
        x,
        z,
        facing,
        speed,
        scale,
        radius,
        clip,
        phase,
        health,
        maxHealth,
        meatRemaining,
        phaseStartedAt,
        hitUntil,
        riderId,
      }) => ({
        id,
        x,
        z,
        facing,
        speed,
        scale,
        radius,
        clip,
        phase,
        health,
        maxHealth,
        meatRemaining,
        phaseStartedAt,
        hitUntil,
        riderId,
        // Exhibition rooms shorten every respawn; the map counts down with it.
        ...(room.rules?.respawnMs != null ? { respawnMs: room.rules.respawnMs } : {}),
      }),
    ),
    enemies: (room.enemies || []).map(
      ({
        id,
        modelKey,
        name,
        hostile,
        x,
        z,
        scale,
        facing,
        speed,
        radius,
        clip,
        phase,
        health,
        maxHealth,
        phaseStartedAt,
        behavior,
        targetId,
        attackSequence,
        attackAt,
        hitSequence,
        hitAt,
        elevation,
        crowRole,
        airborneHeight,
      }) => ({
        id,
        modelKey,
        name,
        hostile,
        x,
        z,
        scale,
        facing,
        speed,
        radius,
        elevation: elevation ?? 0,
        crowRole,
        airborneHeight: airborneHeight ?? 0,
        clip,
        phase,
        health,
        maxHealth,
        phaseStartedAt,
        behavior,
        targetId,
        attackSequence,
        attackAt,
        hitSequence,
        hitAt,
        ...(room.rules?.respawnMs != null ? { respawnMs: room.rules.respawnMs } : {}),
      }),
    ),
    players: [...room.players.values()].map(
      ({
        id,
        name,
        species,
        gender,
        x,
        z,
        radius,
        color,
        inventory,
        gathered,
        tool,
        ready,
        energy,
        facing,
        moving,
        running,
        speed,
        attackSequence,
        attackAt,
        cookingEndsAt,
        jumpAt,
        jumpSequence,
        warpSequence,
        lastExpeditionAt,
        cookingKind,
        fishing,
        coastalActivity,
        spearHead,
        hurtSequence,
        hurtAt,
        defeatSequence,
        downedUntil,
        invulnerableUntil,
        carrierId,
        passengerId,
        carryOfferFromId,
        carryOfferToId,
        carryOfferUntil,
        mountId,
        boatId,
        adventure,
        gulf,
      }) => ({
        id,
        name,
        species,
        gender,
        x,
        z,
        radius,
        color,
        inventory: { ...inventory },
        gathered: gathered ?? 0,
        tool,
        ready,
        energy,
        facing,
        moving,
        running,
        speed,
        attackSequence,
        attackAt,
        cookingEndsAt,
        jumpAt: jumpAt ?? 0,
        jumpSequence: jumpSequence ?? 0,
        warpSequence: warpSequence ?? 0,
        lastExpeditionAt: lastExpeditionAt ?? 0,
        cookingKind,
        fishing: fishing
          ? { spotId: fishing.spotId, startedAt: fishing.startedAt, endsAt: fishing.endsAt }
          : null,
        coastalActivity: coastalActivity
          ? {
              kind: coastalActivity.kind,
              siteId: coastalActivity.siteId,
              startedAt: coastalActivity.startedAt,
              endsAt: coastalActivity.endsAt,
            }
          : null,
        spearHead: spearHead === 'obsidian' ? 'obsidian' : 'wood',
        hurtSequence,
        hurtAt,
        defeatSequence,
        downedUntil,
        invulnerableUntil,
        carrierId,
        passengerId,
        carryOfferFromId,
        carryOfferToId,
        carryOfferUntil,
        mountId,
        boatId,
        adventure: JSON.parse(JSON.stringify(adventure ?? { regions: {} })),
        gulf: gulf ? structuredClone(gulf) : undefined,
      }),
    ),
    ...(includeWorld
      ? {
          resources: room.resources.map(({ regeneratedAt, ...resource }) => ({ ...resource })),
          camp: { ...room.camp },
          cookingFires: room.cookingFires,
          npc: { ...NPC },
          gulf: structuredClone(room.gulf),
        }
      : {}),
    day: villageDay(now, room.createdAt),
    dayProgress: (Math.max(0, now - room.createdAt) % VILLAGE.dayMs) / VILLAGE.dayMs,
    completed: room.camp.level >= 1,
  };
}
