/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare/env.d.ts` (hash: 8c57f47cb22beb298098ce2c48d28c3e)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  SERVICE_ENABLED: 'true';
  GAME: DurableObjectNamespace /* FreeGameRoom */;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'SERVICE_ENABLED'>> {}
}
