"""Build a shared shoreline field from NOAA ETOPO1, preserving the source file.

No meshes are generated here. The field controls placement/clipping of the
existing TRELLIS terrain and water models, and the authoritative coast collider.
Requires only numpy from the bundled Python runtime.
"""
from pathlib import Path
import json, struct, hashlib, sys
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets/geography/source'
raw = (SOURCE / 'etopo1-6min.nc').read_bytes()
assert raw[:3] == b'CDF' and raw[3] in (1, 2), 'Expected classic NetCDF'
offset = 4

def uint():
    global offset
    value = struct.unpack_from('>I', raw, offset)[0]; offset += 4
    return value

def name():
    global offset
    size = uint(); value = raw[offset:offset+size].decode(); offset += (size+3)//4*4
    return value

sizes = {1:1, 2:1, 3:2, 4:4, 5:4, 6:8}
def attributes():
    global offset
    tag, count = uint(), uint()
    assert tag in (0, 12)
    for _ in range(count):
        name(); kind, count = uint(), uint(); offset += (sizes[kind]*count+3)//4*4

assert uint() == 0, 'Record variables are not supported'
tag, count = uint(), uint(); assert tag == 10
dimensions = [(name(), uint()) for _ in range(count)]
attributes()
tag, count = uint(), uint(); assert tag == 11
variables = {}
for _ in range(count):
    key = name(); dim = [uint() for _ in range(uint())]; attributes()
    kind, byte_count = uint(), uint()
    start = uint() if raw[3] == 1 else (uint()<<32) + uint()
    variables[key] = (kind, start, [dimensions[i][1] for i in dim])
kind, start, shape = variables['altitude']; assert kind == 3
elevation = np.frombuffer(raw, dtype='>i2', count=np.prod(shape), offset=start).reshape(shape)
assert shape == [1801,3601] and np.max(elevation) < 30000

row = next(line for line in (SOURCE/'spratt2016-noaa.txt').read_text().splitlines() if line.startswith('50\t'))
sea_level = float(row.split('\t')[1])
width, height, cell = 2048, 1024, 2
# ETOPO latitude increases northwards; the game z-axis increases southwards.
u = (np.arange(width)+.5)/width*(shape[1]-1)
v = (1-(np.arange(height)+.5)/height)*(shape[0]-1)
ix, iz = u.astype(int), v.astype(int)
fx, fz = u-ix, v-iz
e = (elevation[iz[:,None],ix[None,:]]*(1-fx) + elevation[iz[:,None],ix[None,:]+1]*fx)*(1-fz[:,None])
e += (elevation[iz[:,None]+1,ix[None,:]]*(1-fx) + elevation[iz[:,None]+1,ix[None,:]+1]*fx)*fz[:,None]
land = e > sea_level

# Chamfer distance in metres. Boundary samples start half a cell from the edge.
edge = np.zeros(land.shape, dtype=bool)
edge[1:,:] |= land[1:,:] != land[:-1,:]; edge[:-1,:] |= land[1:,:] != land[:-1,:]
edge[:,1:] |= land[:,1:] != land[:,:-1]; edge[:,:-1] |= land[:,1:] != land[:,:-1]
distance = np.where(edge, cell/2, 31.75).astype(np.float32)
for _ in range(23):
    d = distance.copy()
    np.minimum(distance[1:,:], d[:-1,:]+cell, out=distance[1:,:])
    np.minimum(distance[:-1,:], d[1:,:]+cell, out=distance[:-1,:])
    np.minimum(distance[:,1:], d[:,:-1]+cell, out=distance[:,1:])
    np.minimum(distance[:,:-1], d[:,1:]+cell, out=distance[:,:-1])
    for dz,dx in [(1,1),(1,-1),(-1,1),(-1,-1)]:
        a = (slice(1,None) if dz==1 else slice(None,-1), slice(1,None) if dx==1 else slice(None,-1))
        b = (slice(None,-1) if dz==1 else slice(1,None), slice(None,-1) if dx==1 else slice(1,None))
        np.minimum(distance[a], d[b]+cell*2**.5, out=distance[a])
field = np.round(128 + np.where(land, distance, -distance)*4).astype(np.uint8)
flat = field.ravel(); cuts = np.r_[0,np.flatnonzero(flat[1:]!=flat[:-1])+1,flat.size]
runs = np.column_stack((np.diff(cuts),flat[cuts[:-1]])).ravel().tolist()
metadata = {
    'epochYearsBP':50000, 'seaLevelMetres':sea_level, 'seaLevel95PercentMetres':[-84.91,-58.55],
    'width':width,'height':height,'cellMetres':cell,'distanceEncoding':'(byte - 128) / 4 metres; bilinear, cell-centred',
    'projection':'equirectangular, 360 by 180 degrees; not an equal-distance globe',
    'sourceSha256':hashlib.sha256(raw).hexdigest(), 'fieldSha256':hashlib.sha256(field.tobytes()).hexdigest(),
    'landFractionOfProjectedMap':float(land.mean()), 'runCount':len(runs)//2,
    'limitations':['Uniform sea-level cut of modern relief; no glacial isostatic or tectonic correction.',
                   'Small islands and narrow straits below the two-metre game grid can disappear.',
                   'Climate, glacier extents and volcano locations are a simplified game interpretation, not a dated global palaeoclimate reconstruction.']
}
(ROOT/'assets/geography/build.json').write_text(json.dumps(metadata,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
target=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else ROOT/'shared/paleo-coast-data.mjs'
target.parent.mkdir(parents=True,exist_ok=True)
target.write_text('// Generated by scripts/build-paleo-geography.py from public NOAA data. See assets/geography/build.json.\n'
                  + f'export const COAST_GRID = Object.freeze({{ width: {width}, height: {height}, cell: {cell} }});\n'
                  + 'export const COAST_RUNS = '+json.dumps(runs,separators=(',',':'))+';\n',encoding='utf8')
print(json.dumps(metadata))
